#ifndef TCHIRESULT_H
#define TCHIRESULT_H

#include "Rtypes.h" //Root types

const int MAXTEL = 1192; // The chimera telescopes

// The status codes, as generated by kaliveda identification routines for CsI
enum ECode
{
    kICODE0,       // ok
    kICODE1,       // Z ok, mais les masses superieures a A sont possibles
    kICODE2,       // Z ok, mais les masses inferieures a A sont possibles
    kICODE3,       // Z ok, mais les masses superieures ou inferieures a A sont possibles
    kICODE4,       // Z ok, masse hors limit superieure ou egale a A
    kICODE5,       // Z ok, masse hors limit inferieure ou egale a A
    kICODE6,       // au-dessus de la ligne fragment, Z est alors un Zmin
    kICODE7,       // a gauche de la ligne fragment, Z est alors un Zmin et le plus probable
    kICODE8,       // Z indetermine ou (x,y) hors limites
    kICODE9,       // pas de lignes pour ce module [or not valid grids]
    kICODE10,      // gamma
    kICODE_nogrid, // no grid defined, empty pointer
    kICODE_UNSET   // undefined, starting code
};

// Simplified class to extract results for identification procedures
// resembling the KaliVeda class KVIdentificationResult
// This class is declared "friend" of TCHIGridCsi in order to avoid overhead
// Anyway main program or other classes have to use public members to
// access data.

class TCHIResult
{
    friend class TCHIGridCsI; // TCHIGridCsi has full right access to private members
  private:
    Int_t fZ;     // Z of particle found
    Int_t fA;     // A of particle found
    ECode fcod;   // quality code by identification procedure
    Int_t Icod;   // quality code by identification procedure Int_t
    Float_t fPID; // particle pid

    bool fIDOK;   // true if acceptable identification done
    bool fZident; // true if Z established
    bool fAident; // true if A established
    Int_t fStopped;

  public:
    TCHIResult() { Init(); }
    virtual ~TCHIResult() {}
    void Init()
    {
        fZ = -1;
        fA = -1;
        fcod = kICODE8;
        fPID = -1.0;
        fIDOK = false;
        fZident = false;
        fAident = false;
    }
    Int_t GetZ() { return fZ; }
    Int_t GetA() { return fA; }
    void SetA(Int_t A) { fA = A; }
    void SetZ(Int_t Z) { fZ = Z; }
    void Setcod(ECode cod) { fcod = cod; }
    void Setpid(float pid) { fPID = pid; }
    void SetStopped() { fStopped = 1; }
    void SetUnStopped() { fStopped = 0; }
    Int_t GetIfStopped() { return fStopped; }
    ECode Getcod() { return fcod; }
    Int_t GetIcod()
    {
        Int_t icod = -10;
        if (fcod == kICODE0)
            icod = 0;
        if (fcod == kICODE1)
            icod = 1;
        if (fcod == kICODE2)
            icod = 2;
        if (fcod == kICODE3)
            icod = 3;
        if (fcod == kICODE4)
            icod = 4;
        if (fcod == kICODE5)
            icod = 5;
        if (fcod == kICODE6)
            icod = 6;
        if (fcod == kICODE7)
            icod = 7;
        if (fcod == kICODE8)
            icod = 8;
        if (fcod == kICODE9)
            icod = 9;
        if (fcod == kICODE10)
            icod = 10;
        if (fcod == kICODE_nogrid)
            icod = 11;
        if (fcod == kICODE_UNSET)
            icod = 12;
        return icod;
    }
    Double_t GetPID() { return fPID; }
    bool GetIDOK() { return fIDOK; }
    bool GetZident() { return fZident; }
    bool GetAident() { return fAident; }

    // pecoras

    ClassDef(TCHIResult, 1);
};

#endif
