name: static analysis
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

permissions: write-all

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container: 
      image: yanzhaowang/cvmfs_clang:v15
      volumes:
        - /tmp:/cvmfs
      env:
        CVMDIR: /cvmfs/fairsoft.gsi.de
      options: --user root --privileged  --ulimit nofile=10000:10000 --cap-add SYS_ADMIN --device /dev/fuse
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
